//arreglos
let num: number[] = [3,4,8,10,0.3,-45,78,1.54,35.45,45E8,-12];
let number: number[] = [-12,48,56,95,-98,21,5E8,12.54];
let str: string[] = ['hola','amigo','como','estas','espero'];
let pal: string[] = ['ca','elmo','co','na','rro'];
let pala: string[] = ['0001','@_true','sabe','donde','rota'];
let palab: string[] = ['vives','en','un','roca','ciudad'];
let bol: boolean[] = [true,true,true];
let volftt: boolean[] = [false,true,true];
let bolfft: boolean[] = [false,false,true];
let bolfff: boolean[] = [false,false,true];
let num1 =num[2];
let number1= number[3];
let str1=str[0];
let pal2 = pal[1];
let pala1 =pala[2];
let pala2 = pala[3];
let palab1 = palab[0];
let bol1= bol[1] && bol[0] && bol[2];
let volftt1= volftt[1] && volftt[0] && volftt[2];
let bolfft1 = bolfft[1] && bolfft[0] && bolfft[2];
let bolfff1 = bolfff[1] && bolfff[0] && bolfff[2];
enum carro_color{red=1,black=2,orange=0,blue=5,pink=7};
export{num1,number1,str1,pal2,pala1,pala2,palab1,bol1,volftt1,bolfft1,bolfff1,carro_color};